// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package repository

import (
	"github.com/scylladb/gocqlx/v2/table"
	"time"
)

// Table models.
var (
	Pastes = table.New(table.Metadata{
		Name: "pastes",
		Columns: []string{
			"created_at",
			"hash",
			"id",
			"paste",
			"user_id",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{
			"hash",
			"created_at",
		},
	})

	Users = table.New(table.Metadata{
		Name: "users",
		Columns: []string{
			"created_at",
			"email",
			"id",
			"name",
			"password",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{
			"email",
			"created_at",
		},
	})
)

type PastesStruct struct {
	CreatedAt time.Time
	Hash      string
	Id        string
	Paste     string
	UserId    string
}
type UsersStruct struct {
	CreatedAt time.Time
	Email     string
	Id        string
	Name      string
	Password  string
}
